import { Inter } from "next/font/google";
import "./globals.css";

import LayoutProvider from "./components/layoutProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Remi's Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <LayoutProvider>
          {children}
      </LayoutProvider>
      </body>
    </html>
  );
}
